language: node_js
node_js:
  - '0.10'
  - '0.12'
sudo: false
script:
  - npm run lint
  - npm test
after_success:
  - npm install -g codeclimate-test-reporter
  - npm run coverage
  - codeclimate < coverage/lcov.info
