language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 'iojs'
sudo: false
script:
  - npm run lint
  - npm test
after_success:
  - npm install -g codeclimate-test-reporter
  - npm run coverage
  - codeclimate < lcov.info
