language: node_js
node_js:
- '4.2'
- '5'
matrix:
  allow_failures:
  - '5'
sudo: false
script:
- npm run lint
- npm test
- npm run test-integration
after_success:
- npm install -g codeclimate-test-reporter
- npm run coverage
- codeclimate < coverage/lcov.info
- npm run docs
